// TempData.jsx
export const sideNewsData = [
  {
    type: "news",
    newsId: 101,
    stackId: 1,
    title: "पत्नी के चरित्र पर शक, टंगिया से हत्या",
    image: "/images/news1.jpg",
  },
  {
    type: "news",
    newsId: 102,
    stackId: 2,
    title: "बिलासपुर में सड़क हादसा, 2 की मौत",
    image: "/images/tech4.jpg",
  },
  {
    type: "ad",
    adId: "AD-1",
    image: "/images/ad-rect.png",
    link: "https://socialactivitybspnews.blogspot.com/", // ✅ AD LINK
  },
];

// src/data/TempData.jsx

// src/data/TempData.jsx

export const tempCategoryNews = [
  // ---------- POLITICS ----------
  {
    id: "news-101",
    category: "Politics",
    title: "पति के चरित्र पर शक… पत्नी की बेरहमी से हत्या, कोटा में मचा हड़कंप",
    image: "/images/politics1.jpg",
    stackId: "NA",
    uploadedAt: 1704358500000,
  },
  {
    id: "news-102",
    category: "Politics",
    title: "आरोपी पति 48 घंटे में गिरफ्तार, इलाके में दहशत",
    image: "/images/test(2).png",
    stackId: "NA",
    uploadedAt: 1704272100000,
  },
  {
    id: "news-103",
    category: "Politics",
    title: "घरेलू हिंसा के खिलाफ सख्त कानूनों की फिर उठी मांग",
    image: "/images/test(3).png",
    stackId: "NA",
    uploadedAt: 1704185700000,
  },
  {
    id: "news-105",
    category: "Politics",
    title: "विपक्ष ने कानून-व्यवस्था पर सरकार को घेरा",
    image: "/images/test(4).png",
    stackId: "NA",
    uploadedAt: 1704099300000,
  },
  {
    id: "news-107",
    category: "Politics",
    title: "महिला आयोग ने मामले की जांच के दिए आदेश",
    image: "/images/test(5).png",
    stackId: "NA",
    uploadedAt: 1704012900000,
  },
  {
    id: "news-109",
    category: "Politics",
    title: "सामाजिक संगठनों ने दोषी को फांसी की मांग की",
    image: "/images/test(6).png",
    stackId: "NA",
    uploadedAt: 1703926500000,
  },
  {
    id: "news-111",
    category: "Politics",
    title: "महिला अपराधों पर विशेष सत्र बुलाने की मांग",
    image: "/images/test(7).png",
    stackId: "NA",
    uploadedAt: 1703840100000,
  },
  {
    id: "news-113",
    category: "Politics",
    title: "पूर्व मुख्यमंत्री ने घटना को बताया सिस्टम की नाकामी",
    image: "/images/test(8).png",
    stackId: "NA",
    uploadedAt: 1703753700000,
  },
  {
    id: "news-115",
    category: "Politics",
    title: "जनता में आक्रोश, शहर में कैंडल मार्च का आयोजन",
    image: "/images/test(9).png",
    stackId: "NA",
    uploadedAt: 1703667300000,
  },
  {
    id: "news-116",
    category: "Politics",
    title: "राज्य में कानून-व्यवस्था को लेकर हाईलेवल मीटिंग",
    image: "/images/test(10).png",
    stackId: "NA",
    uploadedAt: 1703659000000,
  },
  {
    id: "news-117",
    category: "Politics",
    title: "महिला सुरक्षा पर विपक्ष का विधानसभा में हंगामा",
    image: "/images/test(11).png",
    stackId: "NA",
    uploadedAt: 1703653000000,
  },
  {
    id: "news-118",
    category: "Politics",
    title: "सरकार ने पीड़ित परिवार को आर्थिक सहायता देने का ऐलान",
    image: "/images/test(12).png",
    stackId: "NA",
    uploadedAt: 1703647000000,
  },
  {
    id: "news-119",
    category: "Politics",
    title: "कोटा मामले में SIT जांच की मांग तेज",
    image: "/images/test(13).png",
    stackId: "NA",
    uploadedAt: 1703641000000,
  },

  // ---------- SPORTS ----------
  {
    id: "sports-202",
    category: "Sports",
    title: "रोहित शर्मा की कप्तानी में भारत ने रचा नया इतिहास",
    image: "/images/test(14).png",
    stackId: "NA",
    uploadedAt: 1704358600000,
  },
  {
    id: "sports-207",
    category: "Sports",
    title: "कबड्डी लीग में रोमांचक मुकाबले, दर्शकों में उत्साह",
    image: "/images/test(15).png",
    stackId: "NA",
    uploadedAt: 1704351400000,
  },
  {
    id: "sports-212",
    category: "Sports",
    title: "महिला क्रिकेट टीम की ऐतिहासिक जीत",
    image: "/images/test(16).png",
    stackId: "NA",
    uploadedAt: 1704347800000,
  },
  {
    id: "sports-205",
    category: "Sports",
    title: "फुटबॉल टूर्नामेंट का फाइनल मुकाबला आज",
    image: "/images/test(17).png",
    stackId: "NA",
    uploadedAt: 1704333400000,
  },
  {
    id: "sports-201",
    category: "Sports",
    title: "टीम इंडिया की शानदार जीत, सीरीज पर किया कब्जा",
    image: "/images/test(18).png",
    stackId: "NA",
    uploadedAt: 1704322600000,
  },
  {
    id: "sports-203",
    category: "Sports",
    title: "विराट कोहली ने जड़ा शतक, रिकॉर्ड्स की झड़ी",
    image: "/images/test(19).png",
    stackId: "NA",
    uploadedAt: 1704311800000,
  },
  {
    id: "sports-206",
    category: "Sports",
    title: "ओलंपिक की तैयारी में जुटे भारतीय खिलाड़ी",
    image: "/images/test(20).png",
    stackId: "NA",
    uploadedAt: 1704308200000,
  },
  {
    id: "sports-216",
    category: "Sports",
    title: "IPL नीलामी में युवा खिलाड़ियों पर जमकर पैसा बरसा",
    image: "/images/test(21).png",
    stackId: "NA",
    uploadedAt: 1704302000000,
  },
  {
    id: "sports-217",
    category: "Sports",
    title: "भारतीय बॉक्सर ने अंतरराष्ट्रीय मुकाबले में गोल्ड जीता",
    image: "/images/test(22).png",
    stackId: "NA",
    uploadedAt: 1704296000000,
  },
  {
    id: "sports-218",
    category: "Sports",
    title: "हॉकी लीग में रोमांचक मुकाबले, दर्शकों की भीड़",
    image: "/images/test(23).png",
    stackId: "NA",
    uploadedAt: 1704290000000,
  },
  {
    id: "sports-219",
    category: "Sports",
    title: "फुटबॉल टीम ने कोच बदले जाने का किया ऐलान",
    image: "/images/test(24).png",
    stackId: "NA",
    uploadedAt: 1704284000000,
  },
  {
    id: "sports-220",
    category: "Sports",
    title: "एथलेटिक्स में भारत ने जीते 3 मेडल",
    image: "/images/test(25).png",
    stackId: "NA",
    uploadedAt: 1704278000000,
  },
  {
    id: "sports-221",
    category: "Sports",
    title: "खिलाड़ियों की फिटनेस पर BCCI की सख्ती",
    image: "/images/test(26).png",
    stackId: "NA",
    uploadedAt: 1704272000000,
  },

  // ---------- TECH ----------
  {
    id: "tech-302",
    category: "Tech",
    title: "AI आधारित ऐप ने हेल्थ सेक्टर में मचाया धमाल",
    image: "/images/test(27).png",
    stackId: "NA",
    uploadedAt: 1704359900000,
  },
  {
    id: "tech-306",
    category: "Tech",
    title: "ISRO ने लॉन्च किया नया सैटेलाइट, इंटरनेट होगा तेज",
    image: "/images/test(28).png",
    stackId: "NA",
    uploadedAt: 1704352100000,
  },
  {
    id: "tech-304",
    category: "Tech",
    title: "देश की पहली AI यूनिवर्सिटी खोलने की तैयारी",
    image: "/images/test(29).png",
    stackId: "NA",
    uploadedAt: 1704345800000,
  },
  {
    id: "tech-308",
    category: "Tech",
    title: "WhatsApp ने पेश किया नया प्राइवेसी फीचर",
    image: "/images/test(30).png",
    stackId: "NA",
    uploadedAt: 1704340200000,
  },
  {
    id: "tech-301",
    category: "Tech",
    title: "भारत में 5G विस्तार को लेकर सरकार का बड़ा ऐलान",
    image: "/images/test(31).png",
    stackId: "NA",
    uploadedAt: 1704331200000,
  },
  {
    id: "tech-303",
    category: "Tech",
    title: "साइबर फ्रॉड से बचाव के लिए नई गाइडलाइन जारी",
    image: "/images/test(32).png",
    stackId: "NA",
    uploadedAt: 1704314600000,
  },
  {
    id: "tech-305",
    category: "Tech",
    title: "स्मार्टफोन यूजर्स के लिए नया सिक्योरिटी अलर्ट",
    image: "/images/test(33).png",
    stackId: "NA",
    uploadedAt: 1704309100000,
  },
  {
    id: "tech-316",
    category: "Tech",
    title: "भारत में जल्द शुरू होगी 6G टेक्नोलॉजी की टेस्टिंग",
    image: "/images/test(34).png",
    stackId: "NA",
    uploadedAt: 1704301000000,
  },
  {
    id: "tech-317",
    category: "Tech",
    title: "AI से सरकारी सेवाओं को डिजिटल बनाने की योजना",
    image: "/images/test(35).png",
    stackId: "NA",
    uploadedAt: 1704295000000,
  },
  {
    id: "tech-318",
    category: "Tech",
    title: "साइबर सिक्योरिटी को लेकर स्कूलों में जागरूकता अभियान",
    image: "/images/test(36).png",
    stackId: "NA",
    uploadedAt: 1704289000000,
  },
  {
    id: "tech-319",
    category: "Tech",
    title: "डिजिटल पेमेंट में रिकॉर्ड बढ़ोतरी, UPI फिर अव्वल",
    image: "/images/test(37).png",
    stackId: "NA",
    uploadedAt: 1704283000000,
  },
  {
    id: "tech-320",
    category: "Tech",
    title: "स्टार्टअप्स के लिए नई क्लाउड सब्सिडी योजना",
    image: "/images/test(38).png",
    stackId: "NA",
    uploadedAt: 1704277000000,
  },
  {
    id: "tech-321",
    category: "Tech",
    title: "डेटा लीक मामलों पर सरकार की सख्त निगरानी",
    image: "/images/test(39).png",
    stackId: "NA",
    uploadedAt: 1704271000000,
  },
];
