// TempData.jsx
export const sideNewsData = [
  {
    type: "news",
    newsId: 101,
    stackId: 1,
    title: "पत्नी के चरित्र पर शक, टंगिया से हत्या",
    image: "/images/news1.jpg",
  },
  {
    type: "news",
    newsId: 102,
    stackId: 2,
    title: "बिलासपुर में सड़क हादसा, 2 की मौत",
    image: "/images/news2.jpg",
  },
  {
    type: "ad",
    adId: "AD-1",
    image: "/images/ad-rect.png",
    link: "https://socialactivitybspnews.blogspot.com/", // ✅ AD LINK
  },
];

// src/data/TempData.jsx

// src/data/TempData.jsx

export const tempCategoryNews = [
  {
    id: "news-101",
    category: "Politics",
    title: "पति के चरित्र पर शक… पत्नी की बेरहमी से हत्या, कोटा में मचा हड़कंप",
    newsimg: "/images/politics3.jpg",
    stackId: "NA",
    uploadedAt: 1704358500000,
  },
  {
    id: "news-102",
    category: "Politics",
    title: "आरोपी पति 48 घंटे में गिरफ्तार, इलाके में दहशत",
    newsimg: "/images/politics2.jpg",
    stackId: "NA",
    uploadedAt: 1704272100000,
  },
  {
    id: "news-103",
    category: "Politics",
    title: "घरेलू हिंसा के खिलाफ सख्त कानूनों की फिर उठी मांग",
    newsimg: "/images/BreakingNews5.png",
    stackId: "NA",
    uploadedAt: 1767637209486,
  },
  {
    id: "news-104",
    category: "Politics",
    title: "राज्य सरकार ने महिला सुरक्षा को लेकर की बड़ी घोषणा",
    newsimg: "/images/test (22).jpg",
    stackId: "NA",
    uploadedAt: 1704185700000,
  },
  {
    id: "news-105",
    category: "Politics",
    title: "विपक्ष ने कानून-व्यवस्था पर सरकार को घेरा",
    newsimg: "/images/news1.jpg",
    stackId: "NA",
    uploadedAt: 1704099300000,
  },
  {
    id: "news-106",
    category: "Politics",
    title: "मुख्यमंत्री ने कोटा घटना पर जताया गहरा शोक",
    newsimg: "/images/test (23).jpg",
    stackId: "NA",
    uploadedAt: 1704099300000,
  },
  {
    id: "news-107",
    category: "Politics",
    title: "महिला आयोग ने मामले की जांच के दिए आदेश",
    newsimg: "/images/test (27).jpg",
    stackId: "NA",
    uploadedAt: 1704012900000,
  },
  {
    id: "news-108",
    category: "Politics",
    title: "घटना के बाद शहर में बढ़ाई गई पुलिस पेट्रोलिंग",
    newsimg: "/images/test (31).jpg",
    stackId: "NA",
    uploadedAt: 1704012900000,
  },
  {
    id: "news-109",
    category: "Politics",
    title: "सामाजिक संगठनों ने दोषी को फांसी की मांग की",
    newsimg: "/images/test (37).jpg",
    stackId: "NA",
    uploadedAt: 1703926500000,
  },
  {
    id: "news-110",
    category: "Politics",
    title: "राज्य विधानसभा में गूंजा कोटा हत्याकांड का मुद्दा",
    newsimg: "/images/test (41).jpg",
    stackId: "NA",
    uploadedAt: 1703926500000,
  },
  {
    id: "news-111",
    category: "Politics",
    title: "महिला अपराधों पर विशेष सत्र बुलाने की मांग",
    newsimg: "/images/politics11.jpg",
    stackId: "NA",
    uploadedAt: 1703840100000,
  },
  {
    id: "news-112",
    category: "Politics",
    title: "सरकार ने फास्ट ट्रैक कोर्ट में सुनवाई का भरोसा दिया",
    newsimg: "/images/politics12.jpg",
    stackId: "NA",
    uploadedAt: 1703840100000,
  },
  {
    id: "news-113",
    category: "Politics",
    title: "पूर्व मुख्यमंत्री ने घटना को बताया सिस्टम की नाकामी",
    newsimg: "/images/politics13.jpg",
    stackId: "NA",
    uploadedAt: 1703753700000,
  },
  {
    id: "news-114",
    category: "Politics",
    title: "महिला सुरक्षा को लेकर जल्द नई नीति लाने का संकेत",
    newsimg: "/images/politics14.jpg",
    stackId: "NA",
    uploadedAt: 1703753700000,
  },
  {
    id: "news-115",
    category: "Politics",
    title: "जनता में आक्रोश, शहर में कैंडल मार्च का आयोजन",
    newsimg: "/images/politics15.jpg",
    stackId: "NA",
    uploadedAt: 1703667300000,
  },

  {
    id: "sports-201",
    category: "Sports",
    title: "टीम इंडिया की शानदार जीत, सीरीज पर किया कब्जा",
    newsimg: "/images/sports1.jpg",
    stackId: "NA",
    uploadedAt: 1704322600000,
  },
  {
    id: "sports-202",
    category: "Sports",
    title: "रोहित शर्मा की कप्तानी में भारत ने रचा नया इतिहास",
    newsimg: "/images/test (15).jpg",
    stackId: "NA",
    uploadedAt: 1704358600000,
  },
  {
    id: "sports-203",
    category: "Sports",
    title: "विराट कोहली ने जड़ा शतक, रिकॉर्ड्स की झड़ी",
    newsimg: "/images/sports3.jpg",
    stackId: "NA",
    uploadedAt: 1704311800000,
  },
  {
    id: "sports-204",
    category: "Sports",
    title: "टी20 लीग में युवा खिलाड़ी का धमाकेदार प्रदर्शन",
    newsimg: "/images/test (27).jpg",
    stackId: "NA",
    uploadedAt: 1704344200000,
  },
  {
    id: "sports-205",
    category: "Sports",
    title: "फुटबॉल टूर्नामेंट का फाइनल मुकाबला आज",
    newsimg: "/images/sports13.jpg",
    stackId: "NA",
    uploadedAt: 1704333400000,
  },
  {
    id: "sports-206",
    category: "Sports",
    title: "ओलंपिक की तैयारी में जुटे भारतीय खिलाड़ी",
    newsimg: "/images/sports6.jpg",
    stackId: "NA",
    uploadedAt: 1704308200000,
  },
  {
    id: "sports-207",
    category: "Sports",
    title: "कबड्डी लीग में रोमांचक मुकाबले, दर्शकों में उत्साह",
    newsimg: "/images/test (22).jpg",
    stackId: "NA",
    uploadedAt: 1704351400000,
  },
  {
    id: "sports-208",
    category: "Sports",
    title: "हॉकी टीम ने एशिया कप में बनाई सेमीफाइनल में जगह",
    newsimg: "/images/sports8.jpg",
    stackId: "NA",
    uploadedAt: 1704329800000,
  },
  {
    id: "sports-209",
    category: "Sports",
    title: "बैडमिंटन में भारत को गोल्ड, खिलाड़ी ने बढ़ाया मान",
    newsimg: "/images/test (12).jpg",
    stackId: "NA",
    uploadedAt: 1704340600000,
  },
  {
    id: "sports-210",
    category: "Sports",
    title: "रेसलिंग चैंपियनशिप में भारतीय पहलवान का जलवा",
    newsimg: "/images/sports10.jpg",
    stackId: "NA",
    uploadedAt: 1704315400000,
  },
  {
    id: "sports-211",
    category: "Sports",
    title: "क्रिकेट बोर्ड ने नई चयन नीति की घोषणा की",
    newsimg: "/images/test (18).jpg",
    stackId: "NA",
    uploadedAt: 1704337000000,
  },
  {
    id: "sports-212",
    category: "Sports",
    title: "महिला क्रिकेट टीम की ऐतिहासिक जीत",
    newsimg: "/images/test (19).jpg",
    stackId: "NA",
    uploadedAt: 1704347800000,
  },
  {
    id: "sports-213",
    category: "Sports",
    title: "फिटनेस टेस्ट में फेल होने पर खिलाड़ी बाहर",
    newsimg: "/images/sports13.jpg",
    stackId: "NA",
    uploadedAt: 1704355000000,
  },
  {
    id: "sports-214",
    category: "Sports",
    title: "अंडर-19 टीम ने अंतरराष्ट्रीय टूर्नामेंट जीता",
    newsimg: "/images/test (20).jpg",
    stackId: "NA",
    uploadedAt: 1704326200000,
  },
  {
    id: "sports-215",
    category: "Sports",
    title: "खेल मंत्री ने खिलाड़ियों के लिए नई योजना का ऐलान किया",
    newsimg: "/images/sports15.jpg",
    stackId: "NA",
    uploadedAt: 1704319000000,
  },

  {
    id: "tech-301",
    category: "Tech",
    title: "भारत में 5G विस्तार को लेकर सरकार का बड़ा ऐलान",
    newsimg: "/images/test (33).jpg",
    stackId: "NA",
    uploadedAt: 1704331200000,
  },
  {
    id: "tech-302",
    category: "Tech",
    title: "AI आधारित ऐप ने हेल्थ सेक्टर में मचाया धमाल",
    newsimg: "/images/tech2.jpg",
    stackId: "NA",
    uploadedAt: 1704359900000,
  },
  {
    id: "tech-303",
    category: "Tech",
    title: "साइबर फ्रॉड से बचाव के लिए नई गाइडलाइन जारी",
    newsimg: "/images/tech3.jpg",
    stackId: "NA",
    uploadedAt: 1704314600000,
  },
  {
    id: "tech-304",
    category: "Tech",
    title: "देश की पहली AI यूनिवर्सिटी खोलने की तैयारी",
    newsimg: "/images/tech4.jpg",
    stackId: "NA",
    uploadedAt: 1704345800000,
  },
  {
    id: "tech-305",
    category: "Tech",
    title: "स्मार्टफोन यूजर्स के लिए नया सिक्योरिटी अलर्ट",
    newsimg: "/images/tech5.jpg",
    stackId: "NA",
    uploadedAt: 1704309100000,
  },
  {
    id: "tech-306",
    category: "Tech",
    title: "ISRO ने लॉन्च किया नया सैटेलाइट, इंटरनेट होगा तेज",
    newsimg: "/images/tech6.jpg",
    stackId: "NA",
    uploadedAt: 1704352100000,
  },
  {
    id: "tech-307",
    category: "Tech",
    title: "स्टार्टअप्स के लिए सरकार लाई नई टेक पॉलिसी",
    newsimg: "/images/tech7.jpg",
    stackId: "NA",
    uploadedAt: 1704326400000,
  },
  {
    id: "tech-308",
    category: "Tech",
    title: "WhatsApp ने पेश किया नया प्राइवेसी फीचर",
    newsimg: "/images/tech8.jpg",
    stackId: "NA",
    uploadedAt: 1704340200000,
  },
  {
    id: "tech-309",
    category: "Tech",
    title: "देश में बढ़ रहे साइबर अटैक, एजेंसियां अलर्ट",
    newsimg: "/images/tech9.jpg",
    stackId: "NA",
    uploadedAt: 1704318800000,
  },
  {
    id: "tech-310",
    category: "Tech",
    title: "इलेक्ट्रिक व्हीकल टेक्नोलॉजी में भारत ने लगाई छलांग",
    newsimg: "/images/tech10.jpg",
    stackId: "NA",
    uploadedAt: 1704356500000,
  },
  {
    id: "tech-311",
    category: "Tech",
    title: "UPI यूजर्स के लिए नया नियम आज से लागू",
    newsimg: "/images/test (21).jpg",
    stackId: "NA",
    uploadedAt: 1704329900000,
  },
  {
    id: "tech-312",
    category: "Tech",
    title: "डिजिटल इंडिया मिशन को मिली नई रफ्तार",
    newsimg: "/images/tech9.jpg",
    stackId: "NA",
    uploadedAt: 1704349100000,
  },
  {
    id: "tech-313",
    category: "Tech",
    title: "AI से बने फर्जी वीडियो पर सरकार सख्त",
    newsimg: "/images/tech13.jpg",
    stackId: "NA",
    uploadedAt: 1704311200000,
  },
  {
    id: "tech-314",
    category: "Tech",
    title: "नई टेक्नोलॉजी से किसानों की आय बढ़ाने की योजना",
    newsimg: "/images/test (44).jpg",
    stackId: "NA",
    uploadedAt: 1704337700000,
  },
  {
    id: "tech-315",
    category: "Tech",
    title: "डेटा प्रोटेक्शन कानून पर आई बड़ी अपडेट",
    newsimg: "/images/tech15.jpg",
    stackId: "NA",
    uploadedAt: 1704305500000,
  },
  {
     id: "entertainment-401",
    category: "Entertainment",
    title: "बॉलीवुड स्टार की नई फिल्म ने तोड़ा रिकॉर्ड",
    newsimg: "/images/entertainment1.jpg",
    stackId: "NA",
    uploadedAt: 1704343000023,
  },
  {
    id: "entertainment-402",
    category: "Entertainment",
    title: "म्यूजिक इंडस्ट्री में आया नया ट्रेंड, युवा कलाकारों ने मचाई धूम",
    newsimg: "/images/entertainment2.jpg",
    stackId: "NA",
    uploadedAt: 1704343000010,
  },
  {
    id: "entertainment-403",
    category: "Entertainment",
    title: "टीवी शो ने दर्शकों को किया मंत्रमुग्ध, कहानी ने जीते दिल",
    newsimg: "/images/entertainment3.jpg",
    stackId: "NA",
    uploadedAt: 1704343000120,
  },
  {
    id: "entertainment-404",
    category: "Entertainment",
    title: "फैशन वीक में नए डिजाइनर्स ने दिखाई अपनी प्रतिभा",
    newsimg: "/images/entertainment4.jpg",
    stackId: "NA",
    uploadedAt: 1704343000450,
  },
  {
    id: "entertainment-405",
    category: "Entertainment",
    title: "वेब सीरीज ने सोशल मीडिया पर मचाई धूम, दर्शकों ने किया पसंद",
    newsimg: "/images/entertainment5.jpg",
    stackId: "NA",
    uploadedAt: 1704343000780,
  },
  {
    id: "entertainment-406",
    category: "Entertainment",
    title: "कॉमेडी शो ने दर्शकों को दिया हंसने का मौका",
    newsimg: "/images/entertainment6.jpg",
    stackId: "NA",
    uploadedAt: 1704343000990,
  },
  {
    id: "entertainment-407",
    category: "Entertainment",
    title: "फिल्म फेस्टिवल में अंतरराष्ट्रीय कलाकारों ने बढ़ाया रंग",
    newsimg: "/images/entertainment7.jpg",
    stackId: "NA",
    uploadedAt: 1704343001230,
  },
  {
    id: "entertainment-408",
    category: "Entertainment",
    title: "संगीत समारोह में मशहूर गायक ने दी शानदार प्रस्तुति",
    newsimg: "/images/entertainment8.jpg",
    stackId: "NA",
    uploadedAt: 1704343001450,
    
  },
  {
    id: "entertainment-409",
    category: "Entertainment",
    title: "डांस रियलिटी शो ने युवाओं को किया प्रेरित",
    newsimg: "/images/entertainment9.jpg",
    stackId: "NA",
    uploadedAt: 1704343001670,
  },
  {
    id: "entertainment-410",
    category: "Entertainment",
    title: "नाटक मंडली ने प्रस्तुत किया नया नाटक, दर्शकों ने किया सराहा",
    newsimg: "/images/entertainment10.jpg",
    stackId: "NA",
    uploadedAt: 1704343001890,
  },
];

